### ISSUE TITLE
Hunt Screen UI Issue

### ISSUE THREAD

**Issue by dekay17** [dekay17/darkhorse#21]
Hunt image is appearing at the bottom of the gallery.

![image1 1](https://cloud.githubusercontent.com/assets/7205938/9841416/7f674728-5a6d-11e5-8973-1b8e2dd17ce1.png)

**Comment by themovemaker** [comment]
This issue doesn't seem to be a problem anymore.

**Comment by dekay17** [comment]
may have been version 1
